### ISSUE TITLE
Android App Got Rejection Because of SMS functionality.Please find some good solution for that, Plugin is very useful by the way.

### ISSUE THREAD

**Issue by AamilSilawat** [tazik561/alt_sms_auto_fill#2]

**Comment by tazik561** [comment]
Please send all errors. and reproduce this error in a simple project.

**Comment by Dev-Paccore** [comment]
Issue: Violation of Permissions policy
--
After reviewing your app, we found that it doesn’t qualify to use the requested permissions for the following reason(s):Requested permissions do not match core functionality of the appYou declared Default SMS handler (and any other core functionality usage while default handler) as the core functionality of your app. However, after review, we found that your app does not match the declared use case(s). Learn more about permitted uses and exceptions.Please either:• Make changes to your app so that it meets the requirements of the declared core functionality or,• Select a use case that matches your app’s functionality

Issue: Violation of Permissions policy
After reviewing your app, we found that it doesn’t qualify to use the requested permissions for the following reason(s):
Requested permissions do not match core functionality of the app
You declared Default SMS handler (and any other core functionality usage while default handler) as the core functionality of your app. However, after review, we found that your app does not match the declared use case(s). Learn more about [permitted uses](https://support.google.com/googleplay/android-developer/answer/9047303#intended) and [exceptions](https://support.google.com/googleplay/android-developer/answer/9047303#exceptions).
Please either:
• Make changes to your app so that it meets the requirements of the declared core functionality or,
• [Select a use case](https://support.google.com/googleplay/android-developer/answer/9047303#intended) that matches your app’s functionality

**Comment by Dev-Paccore** [comment]
this is the log from playstore

**Comment by mhdaslam790** [comment]
Any progress?

**Comment by moradiyajay** [comment]
Any solutions ???

**Comment by mahmed743** [comment]
any progress

**Comment by dumparun** [comment]
Google doesnt allow usage of RECIEVE_SMS permission for SMS auto fill any more. you may need to use another API for the same
details below

[Google Support here](https://support.google.com/googleplay/android-developer/answer/10208820#alternatives&zippy=%2Calternatives-to-common-uses
)
